# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 266ce9795f39fdef29492c497129902cab38af1770b87d717c9f70f9039d8e9bdd41afa7ee2ba2e5ccd994b11df2aae5c3d337dbc022916b46155fcb8cd714d6

test:
  secret_key_base: 9db6ab026f71ab284ed7f1de26f323e17c69bd837f306c55c2152571c53402585ca8cb04ac0271e2a34a32df0228d54eb5836aa9d3a3add0417915daa484eec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
